### ISSUE TITLE
doc directory does not build

### ISSUE THREAD

**Issue by libdib** [myemma/EmmaPython#7]
Numerous errors and warning occur when building the docs.
See below:
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.9
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 4 changed, 0 removed
reading sources... [100%] myemma.query                                                                                                                                                                   
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.rst:4: WARNING: autodoc: failed to import module 'myemma'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.rst:9: WARNING: don't know which module to import for autodocumenting 'get_report' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.adapter.rst:4: WARNING: autodoc: failed to import module 'myemma.adapter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.adapter.rst:9: WARNING: autodoc: failed to import module 'myemma.adapter.requests_adapter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:4: WARNING: autodoc: failed to import module 'myemma.model'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:9: WARNING: autodoc: failed to import module 'myemma.model.account'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:16: WARNING: autodoc: failed to import module 'myemma.model.field'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:23: WARNING: autodoc: failed to import module 'myemma.model.group'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:30: WARNING: autodoc: failed to import module 'myemma.model.mailing'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:37: WARNING: autodoc: failed to import module 'myemma.model.member'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:42: WARNING: Title underline too short.

:mod:`member_import` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:42: WARNING: Title underline too short.

:mod:`member_import` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:44: WARNING: autodoc: failed to import module 'myemma.model.member_import'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:49: WARNING: Title underline too short.

:mod:`message` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:49: WARNING: Title underline too short.

:mod:`message` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:51: WARNING: autodoc: failed to import module 'myemma.model.message'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:58: WARNING: autodoc: failed to import module 'myemma.model.search'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:63: WARNING: Title underline too short.

:mod:`trigger` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:63: WARNING: Title underline too short.

:mod:`trigger` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:65: WARNING: autodoc: failed to import module 'myemma.model.trigger'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:70: WARNING: Title underline too short.

:mod:`webhook` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:70: WARNING: Title underline too short.

:mod:`webhook` Module
--------------------
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.model.rst:72: WARNING: autodoc: failed to import module 'myemma.model.webhook'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.query.rst:4: WARNING: autodoc: failed to import module 'myemma.query'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
/Users/Jeffrey/Downloads/EmmaPython-master/doc/myemma.query.rst:9: WARNING: autodoc: failed to import module 'myemma.query.factory'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named 'myemma'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] myemma.query                                                                                                                                                                    
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 25 warnings.

Build finished. The HTML pages are in _build/html.

The resulting _build directory has links but no content.

**Comment by libdib** [comment]
This may be a Python3 issue

**Comment by axisofentropy** [comment]
I think the `doc/` directory was overlooked in the commit that renamed `myemma` to `emma`, 572361927d5b5797803dac0c37a6b2b99c13fadb
